server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5435/maindb
spring.datasource.username=main
spring.datasource.password=12345
spring.sql.init.mode=always
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.show-sql=true