server.port=9090
spring.datasource.url=jdbc:postgresql://stats-db:5432/statsdb
spring.datasource.username=dbuser
spring.datasource.password=12345
spring.sql.init.mode=always
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.show-sql=true